### ISSUE TITLE
Mocks

### ISSUE THREAD

**Issue by xlozinguez** [joostvunderink/angular-jsonrpc-client#1]
Hey @joostvunderink any idea how to mock JSON-RPC calls in a protractor test suite? Trying to use your services and mock responses based on the calls that are made but I'm having difficulties... If you have any idea, I'd greatly appreciate!

**Comment by joostvunderink** [comment]
Hi @xlozinguez. I am not yet familiar with the protractor test suite. My JSON-RPC client is an angular service, just like any other angular service. How would you mock/test another angular service there?

**Comment by joostvunderink** [comment]
Closing issue, as I believe this is not related to the JSON-RPC client but to mocking angular services in protractor in general.
