### ISSUE TITLE
ability to kill a request

### ISSUE THREAD

**Issue by costinh** [joostvunderink/angular-jsonrpc-client#14]
I couldn't find any info about killing an already started request. 
Is this possible?
Thanks

**Comment by joostvunderink** [comment]
This is currently not possible, but a very reasonable feature request. Assuming `$http` supports cancelling a request, I'll implement this.

**Comment by costinh** [comment]
You can use the `timeout` property of the `$http`'s `config` object.

**Comment by joostvunderink** [comment]
This has been implemented in 0.5.0: https://github.com/joostvunderink/angular-jsonrpc-client/releases/tag/0.5.0
