### ISSUE TITLE
Update angular dependency in bower.json

### ISSUE THREAD

**Issue by andrenarchy** [joostvunderink/angular-jsonrpc-client#8]
The angular dependency is outdated (`"angular": "~1.3.15"`). Can you update the dependency to angular 1.4.7 or are there actual incompatibilities?

**Comment by joostvunderink** [comment]
That's a legacy thing - the project I made this for, is using angular 1.3.x. I have just release version 0.2.1, with updated angular dependency (no longer ~1.3.15 but ^1.3.15). I hope this fixes your issue!

**Comment by andrenarchy** [comment]
Perfect, thx!
